# Base docker compose
version: '3'
services:
  web:
    build: ./web
    container_name: web
    depends_on:
      - redis
      - stream
    env_file:
      - secrets.list
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './stream/config/:/stream/config/'
      - './web/bin/:/home/app/bin/'
      - './web/logs/:/home/app/logs/'
  redis:
    container_name: redis
    image: "redis:alpine"
  celery:
    build: ./web
    container_name: celery
    command: su -m celery-user -c "celery -A app.worker.celery_init worker -Q celery,cb:logstash --loglevel=info"
    depends_on:
      - redis
    env_file:
      - secrets.list
    volumes:
      - './web/bin/:/home/app/bin/'
  stream:
    build: ./stream
    container_name: stream
    volumes:
      - './stream/:/home/app'
