# Development config
version: '3'
services:
  web:
    image: cb-flask:dev
    build:
      context: ./web
      dockerfile: Dockerfile
    # Directly expose port 8000 to localhost (don't go through proxy)
    ports:
      - "8000:8000"
    # mount entire source code (necessary for live-reloading)
    volumes:
      - './web/:/home/app'
    env_file:
      - secrets.list
    # debugger support (set breakpoint and run 'docker attach web')
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=cb-dev
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - './elasticsearch/data:/usr/share/elasticsearch/data'
    depends_on:
      - logstash
      - web


