# Base docker compose
version: '3'
services:
  web:
    build: ./web
    container_name: web
    depends_on:
      - redis
      - logstash
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './logstash/config/:/logstash/config/'
      - './web/bin/:/home/app/bin/'
      - './web/logs/:/home/app/logs/'
  redis:
    container_name: redis
    image: "redis:alpine"
  celery:
    build: ./web
    container_name: celery
    command: su -m celery-user -c "celery -A app.worker.celery_init worker -Q celery,cb:logstash --loglevel=info"
    depends_on:
      - redis
    env_file:
      - secrets.list
    volumes:
      - './web/:/home/app'
  logstash:
    build: ./logstash
    container_name: logstash
    environment:
      - LOG_LEVEL=info
      - PIPELINE_WORKERS=1
    volumes:
      - './logstash/config/:/usr/share/logstash/pipeline/:ro'
    depends_on:
      - redis
      - celery

