# Production config
version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.production
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
    env_file:
      - secrets.list
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/passwd/:/etc/nginx/passwd:ro
    command: /bin/bash -c "envsubst '$$API_VIRTUALHOST,$$ES_VIRTUALHOST,$$ELASTICSEARCH_HOST,$$ES_BASICAUTH_PASSWD' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
