# Base docker compose
version: '3'
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '80:80' # expose 80 on host and sent to 80 in container
  #   depends_on:
  #     - web
  web:
    image: cb-flask:production
    depends_on:
      - redis
      - logstash
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './logstash/config/:/logstash/config/'
  redis:
    image: "redis:alpine"
  celery:
    build: ./web
    command: celery -A app.worker.celery_init worker -Q cb:logstash --loglevel=info
    depends_on:
      - redis
    env_file:
      - secrets.list
  logstash:
    build: ./logstash
    environment:
      - LOG_LEVEL=info
      - PIPELINE_WORKERS=1
    volumes:
      - './logstash/config/:/usr/share/logstash/pipeline/:ro'
    depends_on:
      - redis
      - celery

